namespace Skyline.DataMiner.Solutions.MediaOps.Plan.API
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.Net.Messages.SLDataGateway;
    using SLDataGateway.API.Querying;
    using SLDataGateway.API.Types.Querying;

    public static partial class CapabilityExposers
    {
        public static readonly Exposer<Capability, Guid> Id = new Exposer<Capability, Guid>((obj) => obj.Id, "Id");
        public static readonly Exposer<Capability, string> Name = new Exposer<Capability, string>((obj) => obj.Name, "Name");


        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the Skyline.DataMiner.SDM.CodeGenerator package.
        //     Changes to this file will be lost if the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        //namespace Skyline.DataMiner.SDM.Examples.Example3
        //    {
        //        using System;
        //        using System.Collections;
        //        using System.Collections.Generic;
        //        using System.Linq;
        //        using global::Skyline.DataMiner.Net.Messages.SLDataGateway;
        //        using Skyline.DataMiner.Net.Messages.SLDataGateway;
        //        using Skyline.DataMiner.SDM;
        //        using SLDataGateway.API.Querying;
        //        using SLDataGateway.API.Types.Querying;

        //        public static partial class OrderExposers
        //        {
        //            public static readonly Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string> Identifier = new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string>((obj) => obj.Identifier, "Identifier");
        //            public static readonly Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string> CustomerName = new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string>((obj) => obj.CustomerName, "CustomerName");
        //            public static readonly Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, int> Quantity = new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, int>((obj) => obj.Quantity, "Quantity");
        //            public static readonly Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, decimal> TotalAmount = new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, decimal>((obj) => obj.TotalAmount, "TotalAmount");
        //            public static readonly Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, DateTime> OrderDate = new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, DateTime>((obj) => obj.OrderDate, "OrderDate");
        //            public static readonly Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, Skyline.DataMiner.SDM.Examples.Example3.OrderStatus> Status = new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, Skyline.DataMiner.SDM.Examples.Example3.OrderStatus>((obj) => obj.Status, "Status");
        //            public static partial class Product
        //            {
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string> Identifier = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.Identifier).Where(x => x != null), "Product.Identifier"));
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string> Name = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.Name).Where(x => x != null), "Product.Name"));
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string> Description = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.Description).Where(x => x != null), "Product.Description"));
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, decimal> Price = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, decimal>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.Price).Where(x => x != null), "Product.Price"));
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string> Category = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, string>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.Category).Where(x => x != null), "Product.Category"));
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, int> StockQuantity = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, int>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.StockQuantity).Where(x => x != null), "Product.StockQuantity"));
        //                public static readonly DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, DateTime> CreatedDate = DynamicListExposer<Skyline.DataMiner.SDM.Examples.Example3.Order, DateTime>.CreateFromListExposer(new Exposer<Skyline.DataMiner.SDM.Examples.Example3.Order, IEnumerable>((obj) => obj.Product.Where(x => x != null).Select(x => x.CreatedDate).Where(x => x != null), "Product.CreatedDate"));
        //            }
        //        }
        //    }
    }
}
