namespace RT_MediaOps.Plan.Workflow.Jobs
{
	using System;

	using RT_MediaOps.Plan.Extensions;
	using RT_MediaOps.Plan.RegressionTests;

	using Skyline.DataMiner.Solutions.MediaOps.Plan.API;

	[TestClass]
	[TestCategory("IntegrationTest")]
	[DoNotParallelize]
	public sealed class KeyAssignmentTests : IDisposable
	{
		private readonly TestObjectCreator objectCreator;

		public KeyAssignmentTests()
		{
			objectCreator = new TestObjectCreator(TestContext);
		}

		private static IntegrationTestContext TestContext => TestContextManager.SharedTestContext;

		public void Dispose()
		{
			objectCreator.Dispose();
		}

		[TestMethod]
		public void CreateJob_WithUserProvidedKey_KeyIsPreserved()
		{
			var prefix = Guid.NewGuid();
			var userKey = $"RT_{prefix:N}";
			var currentTime = DateTime.Now.RoundToNextSecond();

			var job = new Job
			{
				Name = $"{prefix}_Job",
				Key = userKey,
				Start = currentTime,
				End = currentTime.AddMinutes(5),
			};

			job = objectCreator.CreateJob(job);

			Assert.AreEqual(userKey, job.Key);

			var reread = TestContext.Api.Jobs.Read(job.Id);
			Assert.AreEqual(userKey, reread.Key);
		}

		[TestMethod]
		public void CreateJob_WithoutKey_AutoGeneratedKeyMatchesExpected()
		{
			var prefix = Guid.NewGuid();
			var settings = TestContext.Api.GlobalSettings.GetJobSettings();
			var snapshot = TestContext.CreateJobSettingsSnapshot();

			try
			{
				var expectedKey = $"{snapshot.JobIDPrefix}{snapshot.JobIDNextSequence.ToString().PadLeft(snapshot.JobIDMinimumDigits.HasValue ? (int)snapshot.JobIDMinimumDigits.Value : 1, '0')}";
				var currentTime = DateTime.Now.RoundToNextSecond();

				var job = new Job
				{
					Name = $"{prefix}_Job",
					Start = currentTime,
					End = currentTime.AddMinutes(5),
				};

				Assert.IsTrue(string.IsNullOrEmpty(job.Key), "Key should not be set before creation when auto-generation is expected.");

				job = objectCreator.CreateJob(job);

				Assert.IsFalse(string.IsNullOrEmpty(job.Key), "Auto-generated key should have been assigned during creation.");
				Assert.AreEqual(expectedKey, job.Key, "Auto-generated key did not match the pre-calculated expected value.");

				var reread = TestContext.Api.Jobs.Read(job.Id);
				Assert.AreEqual(expectedKey, reread.Key);
			}
			finally
			{
				TestContext.RestoreJobSettings(snapshot);
			}
		}
	}
}
