namespace RT_MediaOps.Plan.Workflow.Jobs
{
	using System;

	using RT_MediaOps.Plan.RegressionTests;

	using Skyline.DataMiner.Solutions.MediaOps.Plan.API;

	[TestClass]
	[TestCategory("IntegrationTest")]
	[DoNotParallelize]
	public sealed class KeyAssignmentTests : IDisposable
	{
		private readonly TestObjectCreator objectCreator;

		public KeyAssignmentTests()
		{
			objectCreator = new TestObjectCreator(TestContext);
		}

		private static IntegrationTestContext TestContext => TestContextManager.SharedTestContext;

		public void Dispose()
		{
			objectCreator.Dispose();
		}

		[TestMethod]
		public void CreateJob_WithUserProvidedKey_KeyIsPreserved()
		{
			var prefix = Guid.NewGuid();
			var userKey = $"RT_{prefix:N}";

			var job = new Job
			{
				Name = $"{prefix}_Job",
				Key = userKey,
				Start = DateTime.Now,
				End = DateTime.Now.AddMinutes(5),
			};

			job = objectCreator.CreateJob(job);

			Assert.AreEqual(userKey, job.Key);

			var reread = TestContext.Api.Jobs.Read(job.Id);
			Assert.AreEqual(userKey, reread.Key);
		}

		[TestMethod]
		public void CreateJob_WithoutKey_AutoGeneratedKeyMatchesExpected()
		{
			var prefix = Guid.NewGuid();
			var settings = TestContext.Api.GlobalSettings.GetJobSettings();
			var snapshot = Snapshot(settings);

			try
			{
				// Apply deterministic key settings so the next generated key is predictable.
				settings.KeyPrefix = $"RT_{prefix:N}_".Substring(0, 12);
				settings.KeyMinimumDigits = 5;
				settings.KeyStartingSeed = 1;
				settings.KeyIncrement = 1;
				TestContext.Api.GlobalSettings.UpdateJobSettings(settings);

				// Pre-calculate the expected key by reading the current next sequence
				// (the JobSettings update recalculated JobIDNextSequence based on the new starting seed/increment).
				var settingsAfterUpdate = TestContext.Api.GlobalSettings.GetJobSettings();
				var expectedKey = $"{settingsAfterUpdate.KeyPrefix}{settingsAfterUpdate.KeyStartingSeed.ToString().PadLeft(settingsAfterUpdate.KeyMinimumDigits, '0')}";

				var job = new Job
				{
					Name = $"{prefix}_Job",
					Start = DateTime.Now,
					End = DateTime.Now.AddMinutes(5),
				};

				Assert.IsTrue(string.IsNullOrEmpty(job.Key), "Key should not be set before creation when auto-generation is expected.");

				job = objectCreator.CreateJob(job);

				Assert.IsFalse(string.IsNullOrEmpty(job.Key), "Auto-generated key should have been assigned during creation.");
				Assert.AreEqual(expectedKey, job.Key, "Auto-generated key did not match the pre-calculated expected value.");

				var reread = TestContext.Api.Jobs.Read(job.Id);
				Assert.AreEqual(expectedKey, reread.Key);
			}
			finally
			{
				Restore(snapshot);
			}
		}

		private static JobSettingsSnapshot Snapshot(JobSettings settings)
		{
			return new JobSettingsSnapshot
			{
				KeyPrefix = settings.KeyPrefix,
				KeyMinimumDigits = settings.KeyMinimumDigits,
				KeyStartingSeed = settings.KeyStartingSeed,
				KeyIncrement = settings.KeyIncrement,
				DefaultPreRoll = settings.DefaultPreRoll,
				DefaultPostRoll = settings.DefaultPostRoll,
				DesiredJobState = settings.DesiredJobState,
			};
		}

		private static void Restore(JobSettingsSnapshot snapshot)
		{
			var current = TestContext.Api.GlobalSettings.GetJobSettings();
			current.KeyPrefix = snapshot.KeyPrefix;
			current.KeyMinimumDigits = snapshot.KeyMinimumDigits;
			current.KeyStartingSeed = snapshot.KeyStartingSeed;
			current.KeyIncrement = snapshot.KeyIncrement;
			current.DefaultPreRoll = snapshot.DefaultPreRoll;
			current.DefaultPostRoll = snapshot.DefaultPostRoll;
			current.DesiredJobState = snapshot.DesiredJobState;

			TestContext.Api.GlobalSettings.UpdateJobSettings(current);
		}

		private sealed class JobSettingsSnapshot
		{
			public string KeyPrefix { get; set; }

			public int KeyMinimumDigits { get; set; }

			public int KeyStartingSeed { get; set; }

			public int KeyIncrement { get; set; }

			public TimeSpan DefaultPreRoll { get; set; }

			public TimeSpan DefaultPostRoll { get; set; }

			public DesiredJobState DesiredJobState { get; set; }
		}
	}
}
